<a href="https://colab.research.google.com/github/Jaydale3221/practice/blob/main/Numpy_Pandas_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [16]:
# Problem Statement
# You are a data analyst in an education analytics company.
# Your task is to analyze students’ exam performance and provide insights that can help schools, teachers,
# and parents understand factors affecting performance.
# You need to clean, explore, and analyze the dataset using NumPy and Pandas,
#  and summarize your findings with data-driven insights.

In [17]:
df.shape

(1000, 8)

In [18]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [23]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [24]:
# Check for missing values
# df.isnull().sum()
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [25]:
# Check data types
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [26]:
df = df.rename(columns={"math score": "Math", "reading score": "Reading", "writing score": "Writing"})

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Math,Reading,Writing
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df = df.rename(columns = {"Math" : "Maths"})

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Maths,Reading,Writing
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
# Mean, median, max, min
df[["Maths", "Reading", "Writing"]].mean()
df[["Maths", "Reading", "Writing"]].median()
df[["Maths", "Reading", "Writing"]].std()

Maths      15.163080
Reading    14.600192
Writing    15.195657
dtype: float64

In [ ]:
scores = df[["Maths", "Reading", "Writing"]].to_numpy()
np.mean(scores, axis=0)
np.std(scores, axis=0)
np.min(scores, axis=0)
np.max(scores, axis=0)

array([100, 100, 100])

In [ ]:
scores

array([[72, 72, 74],
       [69, 90, 88],
       [90, 95, 93],
       ...,
       [59, 71, 65],
       [68, 78, 77],
       [77, 86, 86]])

In [ ]:
# Filter students who scored > 90 in Math

# df["Maths"] > 90
df[df["Maths"] > 90]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Maths,Reading,Writing
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
121,male,group B,associate's degree,standard,completed,91,89,92
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
233,male,group E,some high school,standard,none,92,87,78
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
306,male,group E,some college,standard,completed,99,87,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
469,male,group C,some college,standard,none,91,74,76
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
521,female,group C,associate's degree,standard,none,91,86,84
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
562,male,group C,bachelor's degree,standard,completed,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
685,female,group E,master's degree,standard,completed,94,99,100
689,male,group E,some college,free/reduced,none,93,90,83
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
719,male,group E,associate's degree,free/reduced,completed,91,73,80
736,male,group C,associate's degree,standard,none,92,79,84
779,male,group E,associate's degree,standard,completed,94,85,82
784,male,group C,bachelor's degree,standard,completed,91,81,79
815,male,group B,some high school,standard,completed,94,86,87
846,male,group C,master's degree,standard,completed,91,85,85
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

In [ ]:
# Filter students with Reading > 80 AND Writing > 80
df[(df["Reading"] > 80) & (df["Writing"] >80)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Maths,Reading,Writing
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
...,...,...,...,...,...,...,...,...
982,male,group B,some high school,standard,completed,79,85,86
983,female,group A,some college,standard,completed,78,87,91
989,female,group D,some college,free/reduced,completed,67,86,83
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [52]:
# .loc and .iloc
# df.loc[0:8, ["Reading"]]
df.iloc[1:8, 2:10]

,parental level of education,lunch,test preparation course,Math,Reading,Writing
1,some college,standard,completed,69,90,88
2,master's degree,standard,none,90,95,93
3,associate's degree,free/reduced,none,47,57,44
4,some college,standard,none,76,78,75
5,associate's degree,standard,none,71,83,78
6,some college,standard,completed,88,95,92
7,some college,free/reduced,none,40,43,39

In [58]:
math_scores = df["Math"].to_numpy()
math_scores[math_scores > 90]

array([ 97,  98,  99,  91, 100,  96,  94,  97,  92,  99,  97,  99, 100,
       100,  91,  94,  95,  91,  97,  92,  96,  92,  91,  92,  94,  95,
       100, 100,  94,  93,  93,  98,  96,  91,  92,  94,  91,  94,  91,
        97,  97,  93,  93, 100,  91,  98,  94,  92, 100,  91])

In [62]:
# Add Total and Average score columns
df["Total"] = df["Math"] + df["Reading"] + df["Writing"]
df["Average"] = df["Total"] / 3

In [63]:
df['Average']

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Name: Average, Length: 1000, dtype: float64

In [67]:
# Categorize Performance
df["Performance"] = pd.cut(df["Average"],
                           bins=[0, 60, 80, 100],
                           labels=["Low", "Medium", "High"])

In [66]:
df['Performance']

0      Medium
1        High
2        High
3         Low
4      Medium
        ...
995      High
996       Low
997    Medium
998    Medium
999      High
Name: Performance, Length: 1000, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [73]:
# Average Math score by gender
# df.groupby("gender")["Math"].mean()
df.groupby("gender")["Math"].mean()

gender
female    63.633205
male      68.728216
Name: Math, dtype: float64

In [74]:
# Multiple aggregations
df.groupby("gender")[["Math","Reading","Writing"]].agg(["mean", "max", "min"])

             Math             Reading             Writing
             mean  max min       mean  max min       mean  max min
gender
female  63.633205  100   0  72.608108  100  17  72.467181  100  10
male    68.728216  100  27  65.473029  100  23  63.311203  100  15

In [77]:
# df.sort_values(by="Total", ascending=False).head()
# Top 5 students by Total score
df.sort_values(by="Total",ascending = False).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Math,Reading,Writing,Total,Average,Performance
916,male,group E,bachelor's degree,standard,completed,100,100,100,300,100.000000,High
962,female,group E,associate's degree,standard,none,100,100,100,300,100.000000,High
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000,High
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,99.666667,High
712,female,group D,some college,standard,none,98,100,99,297,99.000000,High